<php

namespace RM_PagBank\Test\Connect\Payments;

// use RM_PagBank\Connect\Payments\CreditCard; // PHP 5.6 compatibility
// use WC_Helper_Order; // PHP 5.6 compatibility

class CreditCardTest extends \WP_UnitTestCase
{

	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function testPrepare()
    {
		$order = WC_Helper_Order::create_order();
		$order->set_total(100);


    }
}
